name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'weather message'
        required: false

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: GET UP
        run: |
          cargo run get-up ${{ secrets.G_T }} ${{ github.repository }} '${{ github.event.inputs.message }}'

